# Generated by Django 4.2.1 on 2023-05-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeMax', models.IntegerField()),
                ('nom', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=20)),
                ('codepostal', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=17)),
            ],
        ),
    ]
