# Generated by Django 4.2.1 on 2023-05-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_labo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labo',
            name='email',
            field=models.EmailField(default='_', max_length=40),
        ),
    ]
