# Generated by Django 4.2.1 on 2023-05-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_labo_domaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='labo',
            name='dateCreation',
            field=models.DateField(default='1999-12-31'),
        ),
    ]
