# Generated by Django 4.2.1 on 2023-05-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_labo_datecreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=20)),
                ('codepostal', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=17)),
                ('email', models.EmailField(default='_', max_length=40)),
                ('dateEmb', models.DateField(default='1999-12-31')),
            ],
        ),
    ]
