# Generated by Django 4.2.1 on 2023-05-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_perso'),
    ]

    operations = [
        migrations.AddField(
            model_name='labo',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.perso'),
        ),
    ]
