# Generated by Django 4.2.1 on 2023-05-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_labo_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='fonction',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
