# Generated by Django 4.2.1 on 2023-05-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_perso_laboratoire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=20)),
                ('codepostal', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=17)),
                ('email', models.EmailField(default='_', max_length=40)),
                ('dateAdm', models.DateField(default='1999-12-31')),
                ('condition', models.CharField(max_length=30, null=True)),
                ('laboratoire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.labo')),
            ],
        ),
    ]
