# Generated by Django 4.2.1 on 2023-05-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_pat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pat',
            name='condition',
        ),
    ]
