# Generated by Django 4.2.1 on 2023-05-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_pat_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='perso',
            name='salaire',
            field=models.FloatField(max_length=30, null=True),
        ),
    ]
